/**
 * MIT License
 *
 * Copyright (c) [2021] [Rui Eduardo Soares]
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

pipeline {
    agent {
        dockerfile {
            filename 'Dockerfile'
            dir 'tools/dockers/android-sdk'
            args '-u root:root' //todo here because gradlew needs to access root folder /opt
        }
    }
    options {
        skipStagesAfterUnstable()
    }
    parameters {
        gitParameter defaultValue: 'main', description: 'Tag to deploy, eg v0.1.0', name: 'TARGET_TAG', type: 'PT_TAG'
        choice(name: 'RELEASE_TYPE', choices: ['snapshot', 'release'], description: 'Release type')
    }
    stages {
        stage('Assemble') {
            steps {
                sh './gradlew assembleRelease'
            }
        }
        stage('Deploy') {
            steps {
                withCredentials([
                        file(credentialsId: 'mviKotlinGpgSecretRingFile', variable: 'FILE'),
                        string(credentialsId: 'mviKotlinGpgSecretId', variable: 'SECRET_ID'),
                        string(credentialsId: 'mviKotlinGpgSecretPassword', variable: 'SECRET_PASS'),
                        usernamePassword(
                                credentialsId: 'sonatypeNexusCredentials',
                                usernameVariable: 'NEXUS_USERNAME',
                                passwordVariable: 'NEXUS_PASSWORD'
                        )
                ]) {
                    sh "./gradlew app:publishReleasePublicationToMavenRepository -P$RELEASE_TYPE -PossrhUsername=$NEXUS_USERNAME -PossrhPassword=$NEXUS_PASSWORD -Psigning.secretKeyRingFile=\"$FILE\" -Psigning.password=$SECRET_PASS -Psigning.keyId=$SECRET_ID"
                }
            }
        }
    }
    post {
        //Here because we are overriding jenkins user with container root user
        //Always cleanup at the end regardless of pipeline status
        always {
            sh 'rm -R .gradle/ build app/build'
        }
    }
}
