pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    parameters {
        string(name: 'version', defaultValue: '', description: 'Tag version, eg v0.1.0')
        string(name: 'targetBranch', defaultValue: 'main', description: 'Branch from which tag is created, eg release/0.1.0')
    }
    environment {
        TARGET_BRANCH = "${params.targetBranch}"
    }
    stages {
        stage('Create tag') {
            input {
                message "Provide some description for the release"
                parameters {
                    string(name: 'RELEASE_DESCRIPTION', defaultValue: '', description: 'Write some release details')
                }
            }
            steps {
                withCredentials([
                        usernamePassword(
                                credentialsId: 'githubCredentialsAccessToken',
                                usernameVariable: 'GIT_USERNAME',
                                passwordVariable: 'GIT_PASSWORD'
                        )]
                ) {
                    sh "tools/release/github/tag.sh $GIT_USERNAME $GIT_PASSWORD ${params.version}"
                    sh "tools/release/github/release.sh $GIT_USERNAME $GIT_PASSWORD ${params.version} $RELEASE_DESCRIPTION"
                }
            }
        }
    }
}
