pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    parameters {
        string(name: 'version', defaultValue: '', description: 'Tag version, eg v0.1.0')
    }
    stages {
        stage('Create tag') {
            steps {
                sh "tools/release/github/tag.sh ${params.version}"
            }
        }
    }
}
